--- 
port: 5000
servers: 3
docroot: public    
environment: production 
cwd: /data/alonetone/current
log_file: /data/alonetone/current/log/mongrel.log
pid_file: /data/alonetone/pid/mongrel.pid
user: alonetone
group: alonetone



